# Generated by Django 4.0.3 on 2022-07-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=40)),
                ('body', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/welcomeSlide/')),
            ],
        ),
        migrations.DeleteModel(
            name='WelcomeSlider',
        ),
    ]
