# Generated by Django 4.0.3 on 2022-07-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_welcomeslide_delete_welcomeslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='WelcomeSlide',
        ),
    ]
