# Generated by Django 4.0.3 on 2022-07-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_portfolio_delete_welcomeslide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='proj_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, upload_to='portfolios'),
        ),
    ]
