# Generated by Django 4.0.3 on 2022-07-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_proj_name_portfolio_name_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
