# Generated by Django 4.0.3 on 2022-07-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_portfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_first',
            field=models.BooleanField(default=True),
        ),
    ]
